item1 = input('Please enter first item: ')
item2 = input('Please enter second item: ')
item3 = input('Please enter third item: ')
item4 = input('Please enter fourth item: ')
item5 = input('Please enter fifth item: ')
shopping = []
shopping.append(item1)
shopping.append(item2)
shopping.append(item3)
shopping.append(item4)
shopping.append(item5)
print("Your cart items: {}".format(shopping))
removeitem = input("Please enter item to remove: ")
shopping.remove(removeitem)
print("Your cart items: {}".format(shopping))